### ISSUE TITLE
`sandbox-init` doesn't work

### ISSUE THREAD

**Issue by ivan-m** [mrkkrp/ebal#2] opened 2015-08-13 23:24 UTC
When I try and create a sandbox, I'm told a sandbox already exists... when it doesn't.

**Comment by mrkkrp** [comment] 2015-08-14 07:26
Can you provide more information (sequence of actions that I can follow reproduce the bug), because I cannot reproduce this. Maybe you are trying to create a sandbox in sub-directory of existing Cabal project? Here is how it works:
1. Ebal searches for `.cabal` file traversing directories upwards. This allows to perform Cabal commands from any sub-directory/opened file in a project.
2. When you tell it to create sandbox, it needs to check if it already exists. This is currently done by looking for `.cabal-sandbox` directory in root directory of Cabal project.

Thanks.

**Comment by ivan-m** [comment] 2015-08-14 07:33
Well, the sandbox deletion function didn't work either... but trying it in a new repository, `sandbox-init` works as described.

I'm not sure what happened: possibly I was in a situation where the `.cabal-sandbox` directory existed but the `cabal.sandbox.config` didn't or vice versa.

Or possibly I had a `cabal.sandbox.config` but a non-standard sandbox directory (so maybe you should look for `cabal.sandbox.config` rather than `.cabal-sandbox`?).

**Comment by mrkkrp** [comment] 2015-08-14 07:43
> Or possibly I had a cabal.sandbox.config but a non-standard sandbox directory (so maybe you should look for cabal.sandbox.config rather than .cabal-sandbox?).

@ivan-m, This is a good idea, since `cabal.sandbox.config` has information about location of `.cabal-sandbox` (which may be named differently, of course). I have fixed it in  e2e6c80.

**Comment by mrkkrp** [comment] 2015-08-19 09:31
@ivan-m, I'm closing this for now. Feel free to reopen if you experience the problem again.

**Closed as completed** 2015-08-19 09:31 UTC
